apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      kind: PersistentVolume
      name: oai
    patch: |-
      apiVersion: v1
      kind: PersistentVolume
      metadata:
        name: oai
      spec:
        nfs:
          server: 192.168.1.40

images:
  - name: repo/oai:latest
    newName: lttviet/oai
    newTag: v20250303
