x-default: &default
  restart: unless-stopped

services:
  fluentd:
    <<: [*default]
    build:
      context: ./fluentd
      dockerfile: Dockerfile
      args:
        - VERSION=${FLUENTD_TAG}
    container_name: fluentd
    volumes:
      - /mnt/configs/fluentd/log:/fluentd/log
      - /mnt/configs/fluentd/conf:/fluentd/etc
    ports:
      - "24224:24224"
      - "24224:24224/udp"

  elasticsearch:
    <<: *default
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_TAG}
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
    mem_limit: ${MEM_LIMIT}
    volumes:
      - /mnt/configs/elasticsearch:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"

  kibana:
    <<: *default
    user: 1000:1000
    image: docker.elastic.co/kibana/kibana:${STACK_TAG}
    container_name: kibana
    depends_on:
      - elasticsearch
    volumes:
      - /mnt/configs/kibana:/usr/share/kibana/data
    ports:
      - "5601:5601"

  diun:
    <<: *default
    image: crazymax/diun:latest
    container_name: diun
    command: serve
    environment:
      - "TZ=America/New_York"
      - "DIUN_WATCH_WORKERS=20"
      - "DIUN_WATCH_SCHEDULE=0 */6 * * *"
      - "DIUN_WATCH_JITTER=30s"
      - "DIUN_WATCH_FIRSTCHECKNOTIF=true"
      - "DIUN_DEFAULTS_WATCHREPO=true"
      - "DIUN_DEFAULTS_INCLUDETAGS=^latest$"
      - "DIUN_PROVIDERS_DOCKER=true"
      - "DIUN_PROVIDERS_DOCKER_WATCHBYDEFAULT=true"
      - "DIUN_NOTIF_DISCORD_WEBHOOKURL=${DIUN_NOTIF_DISCORD_WEBHOOKURL}"
      - "DIUN_NOTIF_DISCORD_MENTIONS=@here"
    volumes:
      - /home/runner/diun:/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: logger.diun
