apiVersion: v1
kind: PersistentVolume
metadata:
  name: audiobooks
  annotations:
    argocd.argoproj.io/sync-wave: '0'
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    server: 192.168.0.0
    path: '/media'
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: podcasts
  annotations:
    argocd.argoproj.io/sync-wave: '0'
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    server: 192.168.0.0
    path: '/media'
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: configs
  annotations:
    argocd.argoproj.io/sync-wave: '0'
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    server: 192.168.0.0
    path: '/configs'
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: metadata
  annotations:
    argocd.argoproj.io/sync-wave: '0'
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    server: 192.168.0.0
    path: '/data'
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audiobooks
  annotations:
    argocd.argoproj.io/sync-wave: '1'
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  volumeName: audiobooks
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: podcasts
  annotations:
    argocd.argoproj.io/sync-wave: '1'
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  volumeName: podcasts
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: metadata
  annotations:
    argocd.argoproj.io/sync-wave: '1'
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  volumeName: metadata
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: configs
  annotations:
    argocd.argoproj.io/sync-wave: '1'
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  volumeName: configs
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs
