apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cf-api-token
  namespace: external-secrets
  annotations:
    argocd.argoproj.io/sync-wave: '1'
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler

  target:
    name: cf-api-token

  data:
    - secretKey: token
      remoteRef:
        key: CF_API_TOKEN
