apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: blocky-redis
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: '0'
spec:
  project: default
  source:
    repoURL: https://github.com/lttviet/settings.git
    targetRevision: HEAD
    path: k3s/apps/blocky-redis/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: blocky
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: blocky
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: '1'
spec:
  project: default
  source:
    repoURL: https://github.com/lttviet/settings.git
    targetRevision: HEAD
    path: k3s/apps/blocky/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: blocky
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-ui
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: '2'
spec:
  project: default
  source:
    repoURL: https://github.com/lttviet/settings.git
    targetRevision: HEAD
    path: k3s/apps/argocd-ui/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homepage
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: '2'
spec:
  project: default
  source:
    repoURL: https://github.com/lttviet/settings.git
    targetRevision: HEAD
    path: k3s/apps/homepage/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: homepage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sillytavern
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: '2'
spec:
  project: default
  source:
    repoURL: https://github.com/lttviet/settings.git
    targetRevision: HEAD
    path: k3s/apps/sillytavern/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: sillytavern
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oai
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: '2'
spec:
  project: default
  source:
    repoURL: https://github.com/lttviet/settings.git
    targetRevision: HEAD
    path: k3s/apps/oai/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: oai
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cf-tunnel
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: '3'
spec:
  project: default
  source:
    repoURL: https://github.com/lttviet/settings.git
    targetRevision: HEAD
    path: k3s/apps/cf-tunnel/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: cf-tunnel
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
