apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: blocky
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/lttviet/settings.git
    targetRevision: HEAD
    path: k3s/apps/blocky
  destination:
    server: https://kubernetes.default.svc
    namespace: blocky
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: blocky-redis
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/lttviet/settings.git
    targetRevision: HEAD
    path: k3s/apps/blocky-redis
  destination:
    server: https://kubernetes.default.svc
    namespace: blocky
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
