apiVersion: v1
kind: PersistentVolume
metadata:
  name: navidrome
  annotations:
    argocd.argoproj.io/sync-wave: '0'
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    server: 192.168.0.0
    path: '/data'
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: music
  annotations:
    argocd.argoproj.io/sync-wave: '0'
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    server: 192.168.0.0
    path: '/media'
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: navidrome
  annotations:
    argocd.argoproj.io/sync-wave: '1'
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  volumeName: navidrome
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: music
  annotations:
    argocd.argoproj.io/sync-wave: '1'
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  volumeName: music
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs
