apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: lttviet.com
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '0'
spec:
  secretName: lttviet.com
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
    group: cert-manager.io
  commonName: '*.local.lttviet.com'
  dnsNames:
    - '*.local.lttviet.com'
