apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: oai
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    argocd.argoproj.io/sync-wave: '3'
spec:
  tls:
    - hosts:
        - '*.local.lttviet.com'
  rules:
    - host: oai.local.lttviet.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: oai
                port:
                  number: 80
