apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: oai-env
  annotations:
    argocd.argoproj.io/sync-wave: '1'
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    name: oai-env
    template:
      engineVersion: v2
      data:
        NODE_ENV: 'production'
        MAX_CONTEXT_TOKENS_OPENAI: '65536'
        MAX_CONTEXT_TOKENS_ANTHROPIC: '65536'
        MAX_OUTPUT_TOKENS_OPENAI: '2048'
        MAX_OUTPUT_TOKENS_ANTHROPIC: '2048'
        SHOW_TOKEN_COSTS: 'true'
        ALLOWED_MODEL_FAMILIES: 'gemini-flash,gemini-pro,gemini-ultra,aws-claude,aws-claude-opus'
        GOOGLE_AI_KEY: '{{ .gkey }}'
        AWS_CREDENTIALS: '{{ .awskey }}'
  data:
    - secretKey: gkey
      remoteRef:
        key: GOOGLE_AI_KEY
    - secretKey: awskey
      remoteRef:
        key: AWS_SECRET_ACCESS_KEY
