apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: oai-env
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    name: oai-env
    template:
      engineVersion: v2
      templateFrom:
        - configMap:
            name: oai-env-tpl
            items:
              - key: config.yaml
  data:
    - secretKey: google-ai-key
      remoteRef:
        key: GOOGLE_AI_KEY
    - secretKey: aws-secret-access-key
      remoteRef:
        key: AWS_SECRET_ACCESS_KEY
