apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: oai-env
  annotations:
    argocd.argoproj.io/sync-wave: '1'
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    name: oai-env
    template:
      engineVersion: v2
      templateFrom:
        - configMap:
            name: oai-env-tpl
  data:
    - secretKey: gkey
      remoteRef:
        key: GOOGLE_AI_KEY
    - secretKey: awskey
      remoteRef:
        key: AWS_SECRET_ACCESS_KEY
