apiVersion: v1
kind: Service
metadata:
  name: redis
  annotations:
    argocd.argoproj.io/sync-wave: '3'
spec:
  ports:
    - name: db
      port: 6379
      targetPort: 6379
  selector:
    app: redis
