apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis
  annotations:
    argocd.argoproj.io/sync-wave: '0'
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    server: 192.168.28.40
    path: '/data'
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis
  annotations:
    argocd.argoproj.io/sync-wave: '1'
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  volumeName: redis
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs
