---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    email: lttviet@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod-key
    solvers:
    - dns01:
        cloudflare:
          email: lttviet@gmail.com
          apiKeySecretRef:
            name: cf-api-token
            key: token
---
# apiVersion: cert-manager.io/v1
# kind: Certificate
# metadata:
#   name: wildcard-local-domain
# spec:
#   secretName: wildcard-local-domain-tls
#   issuerRef:
#     name: letsencrypt
#     kind: ClusterIssuer
#   dnsNames:
#   - "*.local.lttviet.com"

