apiVersion: v1
kind: Secret
metadata:
    name: remote-auth
    namespace: external-secrets
type: Opaque
stringData:
    doppler-token: ENC[AES256_GCM,data:xarfwuk2XIYvI+1gkeLBDdyyophnhC0brvGRiAwrQVUbJsio+eJ5wDQBuuIJLtOA/ykjcXQ=,iv:HGiAgNCgjwxnKrkRZ2jS1hqeIy+Om1F7y59Q041/vB8=,tag:y0Jd4RuVQGM2jRFM41vTCQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1502nsq9wdlyhf94vdxtzedn4ulsqqr044lhmzdf3775ltvaylstsxw6705
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUWlFlZHFmKzBrQUE3RllT
            OEdhSUNFL1VMb3JPSEQ5ZUJMelpRUUdNZW4wCndwRDFKdEt0Rk4vRTExS1NvUC91
            OEl4NHdiM0Y0ZlZ2ZVYzWitUOW9vRDgKLS0tIDVCOE9OZTBzOFBDbkppaGhqWldI
            dW9PR3VPcXJXWDdUZWNaWHE1S2VyQzQKqBIB9rdlYP5OemMWaOR1QBeBlTbhkcJE
            PCAZSWdmCqYCGjCxcxDIqV+Eemw9uupYTPT6sseeTsmQ3JWZrCI5Pg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-28T06:46:04Z"
    mac: ENC[AES256_GCM,data:7GmuvBTxWhI5joICPgtH1F8+UlqiICnRywBMgZ16+WTIUQVkE2MEp17Ilaxh20XDN7bSf+VLWljKWxz/kIE0NyEYwpMC6zDUgPbGUjkd4S6Rgyc7YORzp4/uygLxiSKoqqHM6uZdrledorriguKgkJs9Xo+pQktNDGQsRB1M8Zg=,iv:sL5Dq6jHNevOuZu6p5XY6IfCxj9zaiHvS7yerzC1TKI=,tag:5p4Sf3wyL2nqFBPeU8XThw==,type:str]
    pgp: []
    encrypted_regex: ^(stringData|data)$
    version: 3.9.2
