apiVersion: v1
kind: Secret
metadata:
    name: cf-token
    namespace: prod
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:55iUOXF2jsITrDxJJYDTJdAQBfE5OXpJGzvyFO+7EQthbU8QWdpsm1oJnHDwgk/byXGoOqHLNGmzqLUIb/6Sfcv5NJMSvuZAUSLO0tUxLMLrN03VIVkaggynpwawHczmmn6H6I0Gsm3V7TltjBLb2PK1SQaYmvd33wIuv8Wz5tZlECw22Yaq/56vG3LXmkV8YbluHxDtm5j5pF/8r+DG+lc+fiaa692s5DTDqxH6QsXJnyLOqfTFKQ==,iv:BTWxndSZ/YGd69FcYYv6nRXBfq907ywGTxRHM8omBhk=,tag:Jj6EwjJWYqnCvxWBRpb45Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1502nsq9wdlyhf94vdxtzedn4ulsqqr044lhmzdf3775ltvaylstsxw6705
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOaGhkd293aERwRHhxSk54
            S293YU9yT1hmWGhxbW5lajR5NmVnQ3VCTVNBCldFdURycTUxR25vMURiT2pMN3RI
            UHYzM0ZKazFQNkVmRW0zS0ZiL2FLeUUKLS0tIDZEMHl0SktnQzRKSXQraGt3bC9w
            Q2x2R20rY2hqQUQrWkYxcTI2blQvZ3MKuK1K4wn67b5/cz52DfbxhuAQ1XFVei0x
            lhhghOUxeNvUrfr0+6A7I1ReIbX2OuIS3ERYKXcS6Y3IDKkr/GdZvQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-03T13:59:06Z"
    mac: ENC[AES256_GCM,data:2niXF3BF3EeLPGpSkVxmb75+0cmPWKLzoE2z8ZVZxWxAKKtULG8almRA4e5Wt775Zf6zwwhVCOdTyq2mZYjlJsrFXA89YBJ0e44c7sP3DfeC5zjqqqzag4ygxxhYFp1OkpkSu/QOTVgbTcO6mmq+n81zvhGf3tNhKOkI5yq2aXY=,iv:329UFWBoP7fhomePZXS87bZ5F6joYMVZA0bndzB1950=,tag:bLmoO0DTdUlQGhH1rWQDyg==,type:str]
    pgp: []
    encrypted_regex: ^(token)$
    version: 3.8.1
