apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '0'

helmCharts:
  - name: cert-manager
    repo: https://charts.jetstack.io
    version: v1.16.2
    releaseName: cert-manager
    namespace: cert-manager
    includeCRDs: true
