apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/cert-manager/cert-manager/releases/download/v1.16.2/cert-manager.yaml

# https://github.com/argoproj/argo-cd/issues/6728
patches:
  - target:
      kind: CustomResourceDefinition
      labelSelector: app.kubernetes.io/instance=cert-manager
    patch: |-
      - op: remove
        path: /metadata/labels/app.kubernetes.io~1instance
