apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# resources:
#   - https://github.com/cert-manager/cert-manager/releases/download/v1.16.2/cert-manager.yaml

helmCharts:
  - name: cert-manager
    repo: https://charts.jetstack.io
    version: v1.16.2
    releaseName: cert-manager
    namespace: cert-manager
    includeCRDs: true
