apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '0'

helmCharts:
  - name: metallb
    repo: https://metallb.github.io/metallb
    version: 0.14.9
    releaseName: metallb
    namespace: metallb-system
    includeCRDs: true
