apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      kind: PersistentVolume
      name: redis
    patch: |-
      apiVersion: v1
      kind: PersistentVolume
      metadata:
        name: redis
      spec:
        nfs:
          server: 192.168.0.30
