apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      kind: PersistentVolume
      name: redis
    patch: |-
      apiVersion: v1
      kind: PersistentVolume
      metadata:
        name: redis
      spec:
        nfs:
          server: 192.168.28.40
  - target:
      kind: Deployment
      name: redis
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: redis
      spec:
        template:
          spec:
            containers:
              - name: redis
                image: redis/redis-stack:7.4.0-v1
