apiVersion: v1
kind: Service
metadata:
  name: blocky-dns-lb
  annotations:
    metallb.universe.tf/address-pool: dns-pool
    argocd.argoproj.io/sync-wave: '2'
spec:
  type: LoadBalancer
  ports:
    - name: dns-tcp
      port: 53
      targetPort: 53
      protocol: TCP
    - name: dns-udp
      port: 53
      targetPort: 53
      protocol: UDP
  selector:
    app: blocky
