apiVersion: v1
kind: Service
metadata:
  name: blocky-dns-http
  annotations:
    argocd.argoproj.io/sync-wave: '2'
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: blocky
