apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: reflector
    repo: https://emberstack.github.io/helm-charts
    version: v7.1.288
    releaseName: reflector
    namespace: kube-system
    includeCRDs: false
