apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: external-secrets
    repo: https://charts.external-secrets.io
    version: v0.12.1
    releaseName: external-secrets
    namespace: external-secrets
    includeCRDs: true
  - name: metallb
    repo: https://metallb.github.io/metallb
    version: 0.14.9
    releaseName: metallb
    namespace: metallb-system
    includeCRDs: true
