---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sillytavern-config
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    server: 192.168.0.40
    path: '/configs'
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sillytavern-data
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    server: 192.168.0.40
    path: '/data'
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sillytavern-config
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  volumeName: sillytavern-config
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sillytavern-data
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  volumeName: sillytavern-data
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs
---

