apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: infisical
spec:
  provider:
    infisical:
      auth:
        universalAuthCredentials:
          clientId:
            key: client-id
            namespace: external-secrets
            name: universal-auth-credentials
          clientSecret:
            key: client-secret
            namespace: external-secrets
            name: universal-auth-credentials
      secretsScope:
        projectSlug: local-37-ev
        environmentSlug: dev
        secretsPath: /OAI
        recursive: true
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: oai-env
spec:
  secretStoreRef:
    kind: SecretStore
    name: infisical
  target:
    name: oai-env
  dataFrom:
    - find:
        name:
          regexp: .*
