apiVersion: v1
kind: ConfigMap
metadata:
  name: oai-greeting
data:
  greeting.md: |
    My personal LLM reverse proxy server!
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: oai
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    server: 192.168.0.40
    path: '/data'
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oai
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  volumeName: oai
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs
