apiVersion: apps/v1
kind: Deployment
metadata:
  name: sillytavern
  labels:
    app: sillytavern
  annotations:
    reloader.stakater.com/auto: 'true'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sillytavern
  template:
    metadata:
      labels:
        app: sillytavern
    spec:
      containers:
        - name: sillytavern
          image: ghcr.io/sillytavern/sillytavern:1.12.12
          env:
            - name: TZ
              value: America/New_York
          ports:
            - name: http
              containerPort: 8000
          volumeMounts:
            - name: sillytavern-config
              mountPath: /home/node/app/config
              subPath: sillytavern
            - name: sillytavern-data
              mountPath: /home/node/app/data
              subPath: sillytavern
      volumes:
        - name: sillytavern-config
          persistentVolumeClaim:
            claimName: sillytavern-config
        - name: sillytavern-data
          persistentVolumeClaim:
            claimName: sillytavern-data
