apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cf-tunnel-token
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    name: cf-tunnel-token
  data:
    - secretKey: token
      remoteRef:
        key: CF_TUNNEL_TOKEN
