apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homepage
  labels:
    app.kubernetes.io/name: homepage
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  tls:
    - hosts:
        - '*.local.lttviet.com'
  rules:
    - host: home.local.lttviet.com
      http:
        paths:
          - path: '/'
            pathType: Prefix
            backend:
              service:
                name: homepage
                port:
                  number: 80
