apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - config-map.yaml
  - cluster-role.yaml
  - deployment.yaml
  - ingress.yaml
  - secret.yaml
  - service.yaml
  - svc-acc.yaml
