x-default: &default
  restart: unless-stopped

services:
  wg-easy:
    <<: *default
    image: ghcr.io/wg-easy/wg-easy:${WG_TAG}
    environment:
      - WG_HOST=${WG_HOST}
      - PASSWORD=${WG_PASSWORD}
      - WG_DEFAULT_DNS=${WG_DEFAULT_DNS}
    container_name: wg-easy
    volumes:
      - /mnt/configs/wg-easy:/etc/wireguard
    ports:
      - "51820:51820/udp"
      - "80:51821/tcp"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    logging:
      driver: "fluentd"
      options:
        fluentd-address: ${FLUENTD_HOST}
        tag: wg-easy

  diun:
    <<: *default
    image: crazymax/diun:latest
    container_name: diun
    command: serve
    environment:
      - "TZ=America/New_York"
      - "DIUN_WATCH_WORKERS=20"
      - "DIUN_WATCH_SCHEDULE=0 */6 * * *"
      - "DIUN_WATCH_JITTER=30s"
      - "DIUN_WATCH_FIRSTCHECKNOTIF=true"
      - "DIUN_DEFAULTS_WATCHREPO=true"
      - "DIUN_DEFAULTS_INCLUDETAGS=^latest$"
      - "DIUN_PROVIDERS_DOCKER=true"
      - "DIUN_PROVIDERS_DOCKER_WATCHBYDEFAULT=true"
      - "DIUN_NOTIF_DISCORD_WEBHOOKURL=${DIUN_NOTIF_DISCORD_WEBHOOKURL}"
      - "DIUN_NOTIF_DISCORD_MENTIONS=@here"
    volumes:
      - /home/runner/diun:/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
    logging:
      driver: "fluentd"
      options:
        fluentd-address: ${FLUENTD_HOST}
        tag: wg-easy.diun
