apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: cert-manager
    repo: https://charts.jetstack.io
    version: v1.17.0
    releaseName: cert-manager
    namespace: cert-manager
    includeCRDs: true

# https://github.com/argoproj/argo-cd/issues/6728
patches:
  - target:
      kind: CustomResourceDefinition
      labelSelector: app.kubernetes.io/instance=cert-manager
    patch: |-
      - op: remove
        path: /metadata/labels/app.kubernetes.io~1instance
