apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: blocky
  labels:
    app: blocky-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blocky-redis
  template:
    metadata:
      labels:
        app: blocky-redis
    spec:
      containers:
        - name: redis
          image: redis:8.0-M02
          ports:
            - name: database
              containerPort: 6379
          volumeMounts:
            - name: storage
              mountPath: /data
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: redis
