services:
    adguard-home:
        restart: unless-stopped
        image: adguard/adguardhome:latest
        network_mode: host
        container_name: adguard-home
        volumes:
            - /nfs/configs/adguard/work:/opt/adguardhome/work
            - /nfs/configs/adguard/conf:/opt/adguardhome/conf
        logging:
            driver: local
    adguardhome-sync:
        restart: unless-stopped
        image: ghcr.io/bakito/adguardhome-sync
        container_name: adguardhome-sync
        command: run
        environment:
            LOG_LEVEL: info
            ORIGIN_URL: http://192.168.0.21
            ORIGIN_USERNAME: ENC[AES256_GCM,data:F74DC2g=,iv:v9Dg8MGiRPJ3VOiyVJkHT6Y2UEEM0OcnzABMxiIdJ9k=,tag:2YJGSsVdXk1ecmH23bwS1w==,type:str]
            ORIGIN_PASSWORD: ENC[AES256_GCM,data:n9oreTYYHhjqr1s=,iv:wuUmgMtILcZ99F631eKkPzPNRJOKgViq/jB/aOICiVE=,tag:8eNUh3LU/Go+Nd/i/79ytQ==,type:str]
            REPLICA1_URL: http://192.168.0.20
            REPLICA1_USERNAME: ENC[AES256_GCM,data:N25eTMo=,iv:BTWOWNhSrairqaKHq5OVb4i+SB9OXg4Yg///zAX2aqY=,tag:Q7q8f4KILwMQapi7UUbGdA==,type:str]
            REPLICA1_PASSWORD: ENC[AES256_GCM,data:1CTCJqE5TYfsxZI=,iv:IjtFVZfUsgX6y9nOGnohKgiqctjwJKwS/WsyuppsW4k=,tag:Zj6N93ptqLcwi7AzrBtoqQ==,type:str]
            # run every 10 minutes
            CRON: 0 */2 * * *
            API_PORT: 8080
        ports:
            - 8080:8080
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1502nsq9wdlyhf94vdxtzedn4ulsqqr044lhmzdf3775ltvaylstsxw6705
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLaWtjWWViaHEvMHZseEx1
            MTRXaWc3N1ZNbWljZmpQSkdTUmJnTlcrSkVFCmNibXZiYTdQeHZFNmFCQmtWRkk1
            MUROQXQvcGdLV2ExcDJWdEVhWnIyKzAKLS0tIDd6ZU5kMERrZElpMjU3QmFiUERO
            TWRTQXkwRnBaMEZHcE5JMUFBUUdoT00KbsOmNeBCLVf1qnbaymK03K+aGSRLHJW3
            a0ByLbT+9QodQIczV/sRN+e1H1NqYZEkA9XcaiBkJeFqgoPexWnyoA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-23T06:51:46Z"
    mac: ENC[AES256_GCM,data:Co0b4wMyojsauKBTNMojPIScnl9jrnCmazmi3t8r1s8kGWTB4EYGUcn/RNy/N2WpVh/76Sw5GV4BIE92wafkMcSVgR22iVlmgogKCzwPnu6YPaPIOVu48XU8rAyfVPOcx+GFInR4+tB61Q+8Fxa2jQm9meSWky2K+VZwtXqZyvg=,iv:EsejVphQ1nEb/oTMqirtLS85QD6+POqDHHQBcTECW0I=,tag:GPrzMjK6Qqw27pj85LN7SQ==,type:str]
    pgp: []
    encrypted_regex: ^(.*USERNAME|.*PASSWORD)$
    version: 3.8.1
