apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      kind: PersistentVolume
      name: suwayomi
    patch: |-
      apiVersion: v1
      kind: PersistentVolume
      metadata:
        name: suwayomi
      spec:
        nfs:
          server: 192.168.1.40

images:
  - name: ghcr.io/suwayomi/tachidesk:v1.1.1-r1689
    newTag: v2.0.1864
