apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: infisical
spec:
  provider:
    infisical:
      auth:
        universalAuthCredentials:
          clientId:
            key: client-id
            namespace: external-secrets
            name: infisical-auth
          clientSecret:
            key: client-secret
            namespace: external-secrets
            name: infisical-auth
      secretsScope:
        projectSlug: local-37-ev
        environmentSlug: dev
        secretsPath: /
        recursive: true
