apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: metallb-system

resources:
  - github.com/metallb/metallb/config/native?ref=v0.14.9
  - traefik-ip-pool.yaml
  - dns-ip-pool.yaml
  - l2-ad.yaml
