apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cf-api-token
  namespace: cert-manager
  annotations:
    argocd.argoproj.io/sync-wave: '1'
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    name: cf-api-token
  data:
    - secretKey: token
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: CF_API_TOKEN
        metadataPolicy: None
