# use local dns for *.local.lttviet.com
apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  lttviet.server: |
    local.lttviet.com.:53 {
      forward . 192.168.28.30
    }
