- hosts: k3s_servers
  tasks:
    - name: Install K3S server
      shell: >
        curl -sfL https://get.k3s.io |
        sh -s - server --cluster-init
        --disable servicelb
        --kube-proxy-arg proxy-mode=ipvs
        --kube-proxy-arg ipvs-strict-arp
      environment:
        K3S_TOKEN: '{{ k3s_token }}'
      args:
        creates: /usr/local/bin/k3s

- hosts: k3s_servers[0]
  vars:
    k3s_server: "{{ groups['k3s_servers'][0] }}"
    k3s_url: "https://{{ hostvars[k3s_server]['ansible_host'] }}:6443"
  tasks:
    - name: Display K3S config
      shell: k3s kubectl config view --raw
      become: true
      register: config_output
    - name: Update server URL in config
      set_fact:
        updated_config: "{{ config_output.stdout | regex_replace('server: .*', 'server: ' + k3s_url) }}"
    - name: Copy K3S config to local.
      copy:
        content: '{{ updated_config }}'
        dest: '/home/viet/.kube/config'
      delegate_to: localhost

- hosts: k3s_agents
  vars:
    k3s_server: "{{ groups['k3s_servers'][0] }}"
    k3s_url: "https://{{ hostvars[k3s_server]['ansible_host'] }}:6443"
  tasks:
    - name: Install K3S agent
      shell: >
        curl -sfL https://get.k3s.io |
        sh -s - agent
      environment:
        K3S_TOKEN: '{{ k3s_token }}'
        K3S_URL: '{{ k3s_url }}'
      args:
        creates: /usr/local/bin/k3s
