- name: Update dockers and up
  hosts: behind-reverse-proxy
  tasks:
    - name: Copy compose and env files
      ansible.builtin.copy:
        src: /mnt/configs/settings/docker-compose/behind-reverse-proxy/
        dest: /home/runner
        mode: "0644"
    - name: Run `docker-compose up`
      community.docker.docker_compose_v2:
        project_src: /home/runner
        pull: always
        build: always
      register: output
    - name: Show results
      ansible.builtin.debug:
        var: output
