apiVersion: v1
kind: PersistentVolume
metadata:
  name: suwayomi-data
  annotations:
    argocd.argoproj.io/sync-wave: '0'
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    server: 192.168.0.40
    path: '/data'
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: suwayomi-download
  annotations:
    argocd.argoproj.io/sync-wave: '0'
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    server: 192.168.0.40
    path: '/download'
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: suwayomi-data
  annotations:
    argocd.argoproj.io/sync-wave: '1'
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  volumeName: suwayomi-data
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: suwayomi-download
  annotations:
    argocd.argoproj.io/sync-wave: '1'
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  volumeName: suwayomi-download
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs
