services:
  cloudflared:
    image: cloudflare/cloudflared:${CLOUDFLARED_TAG}
    restart: unless-stopped
    container_name: cloudflared
    command: tunnel --no-autoupdate run --token ${CLOUDFLARED_TOKEN}

  diun:
    image: crazymax/diun:latest
    restart: unless-stopped
    container_name: diun
    command: serve
    environment:
      - "TZ=America/New_York"
      - "DIUN_WATCH_WORKERS=20"
      - "DIUN_WATCH_SCHEDULE=0 */6 * * *"
      - "DIUN_WATCH_JITTER=30s"
      - "DIUN_WATCH_FIRSTCHECKNOTIF=true"
      - "DIUN_DEFAULTS_WATCHREPO=true"
      - "DIUN_DEFAULTS_INCLUDETAGS=^latest$"
      - "DIUN_PROVIDERS_DOCKER=true"
      - "DIUN_PROVIDERS_DOCKER_WATCHBYDEFAULT=true"
      - "DIUN_NOTIF_DISCORD_WEBHOOKURL=${DIUN_NOTIF_DISCORD_WEBHOOKURL}"
      - "DIUN_NOTIF_DISCORD_MENTIONS=@here"
    volumes:
      - /home/runner/diun:/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
